import Head from "next/head";
import AboutMe from "../components/AboutMe";
import ContactMe from "../components/ContactMe";
import Header from "../components/Header";
import Portfolio from "../components/Portfolio";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <AboutMe />
      <Portfolio />
      <ContactMe />
    </div>
  );
}
